### ISSUE TITLE
Unreal's T3d predates your t3d. Yea you stole it.

### ISSUE THREAD

**Issue by chaosesqueteam** [RichardRanft/T3DKeyMapMod#2]
Unreal's T3d predates your t3d. Yea you stole it.

**Comment by chaosesqueteam** [comment]
BaZed Unreal 1997, hot nahhh seven blastin on da impala.
Coloured lighting.
ASCII format.
EZ-E parsing.

Then "years later", what like 2 decades? you DECIDE to fking steal the name
"NOO I DIDNT BECAUSE THIS IS NOW (more years later) OLD PROJCT!"
Yes you did

**Comment by RichardRanft** [comment]
**This project isn't a game engine.**  
Not even close.  
It's a utility to update a default script within the Torque 3D game engine.  All of this noise and you haven't even read the README or the code.  You have literally no idea what you're rambling about.

**Comment by RichardRanft** [comment]
@chaosesqueteam 
I just realized what you thought you were talking about.  A _file format_ used in Unreal Engine.  Great.  So, here's the thing - 

https://torque3d.org

As it turns out, the old Torque Game Engine (TGE) grew into Torque Game Engine: Advanced (TGEA), and then eventually into Torque 3D (T3D).  Another funny thing here is that I didn't create any of that, though I did work at Garage Games for a few years.

Funny thing here; this has absolutely nothing to do with Unreal Engine.

Corollary -
The Torque family of engines have used the .cs extension for their scripts for a long time.  Then Microsoft came along and made C#, using the .cs extension for C# source files.  "Oh no!  Microsoft stole my format extension!"

Moral of the story:  Please do some research before blasting ludicrous and unhinged assertions.

**Comment by RichardRanft** [comment]
@chaosesqueteam 

More information for you, though I doubt you're too inclined to actually read - 

https://en.wikipedia.org/wiki/Torque_(game_engine)

**Comment by chaosesqueteam** [comment]
I saw Torque come, and I saw Torque go.
Yes microsoft did steal that format extension.
Just as you stole the t3d name.

And BTW: I am a lawyer: now neither of these things are trademarked; but the fact is that your arguments are not logical
"The Torque family of engines have used the .cs extension for their scripts for a long time. Then Microsoft came along and made C#, using the .cs extension for C# source files. "Oh no! Microsoft stole my format extension!""

This is correct: Microsoft stole that extension.

**Comment by chaosesqueteam** [comment]
> **This project isn't a game engine.** 
I remeber Torque3d being announced on slashdot. So don't pretend I don't know what bullshit you're talking about.
The fact is t3d is unreal's. I have to sift through 100s of torque3d bullshit because you fucks were too lazy to type a few more letters, and too ignorant of the history of 3d.

Unreal was the first widespread 3d game engine with coloured lighting.
You spit on it by associating your later also-ran torque 3d bullshit engine. Which came. Which went.
t3d is Unreal's
